// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"time"
)

type AuthResponse struct {
	AccessToken string `json:"accessToken"`
	User        *User  `json:"user"`
}

type CreatePostInput struct {
	Body string `json:"body"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Post struct {
	ID        string    `json:"id"`
	Body      string    `json:"body"`
	Username  string    `json:"username"`
	User      *User     `json:"user"`
	UserID    string    `json:"userID"`
	CreatedAt time.Time `json:"createdAt"`
}

type RegisterInput struct {
	Email           string `json:"email"`
	Username        string `json:"username"`
	Password        string `json:"password"`
	ConfirmPassword string `json:"confirmPassword"`
}

type User struct {
	ID        string    `json:"id"`
	Username  string    `json:"username"`
	Email     string    `json:"email"`
	Password  string    `json:"password"`
	CreatedAt time.Time `json:"createdAt"`
}
