// Code generated by mockery v2.33.1. DO NOT EDIT.

package mocks

import (
	context "context"

	jwt "github.com/RianNegreiros/go-graphql-api/internal/jwt"
	mock "github.com/stretchr/testify/mock"
)

// RefreshTokenRepo is an autogenerated mock type for the RefreshTokenRepo type
type RefreshTokenRepo struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, params
func (_m *RefreshTokenRepo) Create(ctx context.Context, params jwt.CreateRefreshTokenParams) (jwt.RefreshToken, error) {
	ret := _m.Called(ctx, params)

	var r0 jwt.RefreshToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, jwt.CreateRefreshTokenParams) (jwt.RefreshToken, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, jwt.CreateRefreshTokenParams) jwt.RefreshToken); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Get(0).(jwt.RefreshToken)
	}

	if rf, ok := ret.Get(1).(func(context.Context, jwt.CreateRefreshTokenParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *RefreshTokenRepo) GetByID(ctx context.Context, id string) (jwt.RefreshToken, error) {
	ret := _m.Called(ctx, id)

	var r0 jwt.RefreshToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (jwt.RefreshToken, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) jwt.RefreshToken); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(jwt.RefreshToken)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRefreshTokenRepo creates a new instance of RefreshTokenRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRefreshTokenRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *RefreshTokenRepo {
	mock := &RefreshTokenRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
